# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-28 00:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0029_auto_20171026_1823'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=9)),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('pagado', models.BooleanField(default=False)),
                ('conekta', models.CharField(blank=True, max_length=140, null=True)),
                ('extra', models.CharField(blank=True, max_length=1, null=True)),
                ('donador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donaciones', to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donaciones', to='projects.Project')),
                ('recompensa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donaciones', to='projects.Reward')),
            ],
        ),
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('date', models.DateTimeField(auto_now=True)),
                ('paid', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='projects.Project')),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='projects.Reward')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
