# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-27 21:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0029_auto_20171026_1823'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('pagado', models.BooleanField(default=False)),
                ('donador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donaciones', to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donaciones', to='projects.Project')),
                ('recompensa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donaciones', to='projects.Reward')),
            ],
        ),
    ]
