# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-27 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_donacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='donacion',
            name='monto',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=9),
            preserve_default=False,
        ),
    ]
