# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-27 23:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_donacion_monto'),
    ]

    operations = [
        migrations.AddField(
            model_name='donacion',
            name='conekta',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
