# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-28 00:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_donacion_conekta'),
    ]

    operations = [
        migrations.AddField(
            model_name='donacion',
            name='extra',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
