# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-31 18:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20170531_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
    ]
