# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-05 22:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20170603_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('editing', 'Editando'), ('review', 'Revisando'), ('rejected', 'Rechazado'), ('approved', 'Aprobado')], default='editing', max_length=140),
        ),
    ]
