# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-12 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_project_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.ManyToManyField(related_name='projects', to='projects.Category'),
        ),
    ]
