# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-12 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20170612_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='lol', max_length=250),
            preserve_default=False,
        ),
    ]
