# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-14 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='photoURL',
            field=models.URLField(blank=True, null=True),
        ),
    ]
