# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-15 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_project_photourl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.ManyToManyField(default='salud', related_name='projects', to='projects.Category'),
        ),
    ]
