# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-15 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20170615_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.ManyToManyField(default=1, related_name='projects', to='projects.Category'),
        ),
    ]
