# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-17 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20170615_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.ManyToManyField(related_name='projects', to='projects.Category'),
        ),
    ]
