# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-19 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_auto_20170617_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reward',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='validated',
            field=models.BooleanField(default=True),
        ),
    ]
