# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-19 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_auto_20170619_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, max_length=240, null=True),
        ),
    ]
