# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-11 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_project_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='summary',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
