# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-11 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_auto_20170711_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='goal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='photo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
