# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-12 00:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0021_remove_project_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='followers',
            field=models.ManyToManyField(blank=True, through='projects.Follow', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='follow',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_to_set', to='projects.Project'),
        ),
    ]
