# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-12 01:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_auto_20170711_2001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='user_from',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='updates',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updater', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='updates',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='projects.Project'),
        ),
    ]
