# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-12 01:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_auto_20170711_2002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='username',
            new_name='user_from',
        ),
    ]
