# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-12 01:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0025_auto_20170711_2008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='user_from',
            new_name='user',
        ),
    ]
