# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-12 03:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_auto_20170711_1506'),
        ('projects', '0027_auto_20170711_2102'),
    ]

    operations = [
    ]
