# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-14 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0028_merge_20170711_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updates',
            name='image',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
