# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-06 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0029_auto_20171026_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='validated',
            field=models.BooleanField(default=False),
        ),
    ]
