# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-17 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0029_auto_20170714_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='updates',
            name='date',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
    ]
