# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-17 21:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0030_updates_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updates',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='projects.Project'),
        ),
    ]
