# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-17 21:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0031_auto_20170717_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updates',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updater', to=settings.AUTH_USER_MODEL),
        ),
    ]
