# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-07 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0031_project_destacado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, related_name='projects', to='projects.Category'),
        ),
    ]
