# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-07 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0032_auto_20171107_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='goal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='reward',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
