# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-13 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0033_auto_20171107_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='description',
            field=models.TextField(),
        ),
    ]
