# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-13 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0034_auto_20171113_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updates',
            name='update',
            field=models.TextField(blank=True, null=True),
        ),
    ]
