# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-14 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20170603_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photoURL',
            field=models.URLField(blank=True, null=True),
        ),
    ]
