# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-14 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_photourl'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='canPublish',
            field=models.BooleanField(default=False),
        ),
    ]
