# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-16 17:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20170603_2322'),
        ('accounts', '0004_profile_canpublish'),
    ]

    operations = [
    ]
