# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-26 04:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20170617_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='uid',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
