# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-26 23:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_profile_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='conekta',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
