# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-07 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_profile_conekta'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='provider_uid',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
